### ISSUE TITLE
installed file needs to be placed in project root

### ISSUE THREAD

**Issue by chrisnx** [wearebase/base-bash-bosh#4]
When bosh install is run, a blank file called installed is created in the bosh directory (vendor/wearebase/bosh). This file disappears each time you run composer update.

The file needs to place itself and be looked for in the projects root somewhere instead. Eg. config/bosh-installed

**Comment by rossey** [comment]
Maybe it should create a `Boshfile` in the top level of the project

**Comment by chrisnx** [comment]
Actually it makes a bosh-config file (could be renamed to boshFile) so it could just check for that instead

**Comment by chrisnx** [comment]
Resolved in https://github.com/wearebase/base-bash-bosh/releases/tag/v1.0.18
