### ISSUE TITLE
Add boshify / ansible script

### ISSUE THREAD

**Issue by chrisnx** [wearebase/base-bash-bosh#8]
Add a script that will ssh into a server and create the folders required for bosh to work.
Also add a simple playbook to do this.

**Comment by dave1010** [comment]
Bosh already knows about the envs, so it may not need provisioning. How about this?

```
bosh remote-install production
```

**Comment by chrisnx** [comment]
Thanks @dave1010 good idea

**Comment by chrisnx** [comment]
0f8532d7dccf68da7b592fc7552094ca6670ef3b added bosh script to setup project structure
